name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    name: rake ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '.ruby-version'
          bundler-cache: true

      - name: rake ci
        run: bundle exec rake ci
        env:
          NO_COLOR: '1'
          AOC_ASCII: '1'
